#Dockerfile.amd64
FROM adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine
VOLUME /app
ADD target/app.jar /app/app.jar
WORKDIR /app
#ÉèÖÃÊ±Çø
RUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.12/main/ > /etc/apk/repositories && \
apk --update add tzdata && \
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
echo "Asia/Shanghai" > /etc/timezone && \
apk add --update ttf-dejavu fontconfig && \
apk del tzdata && \
rm -rf /var/cache/apk/*

CMD "java" "-jar" "app.jar"